### ISSUE TITLE
Subscribers parameter is not working on load test

### ISSUE THREAD

**Issue by eyyupbgds** [livekit/livekit-cli#125]
![Screen Shot 2022-11-10 at 14 38 12](https://user-images.githubusercontent.com/95404717/201082771-0f9eee80-e4be-488e-b3c7-c16f84365285.png)

When not add --subscribers parameter to load test command, duration is working and it is ending after given time.

![Screen Shot 2022-11-10 at 14 40 45](https://user-images.githubusercontent.com/95404717/201082780-1de1b40c-3cce-4a02-bcf9-850d3514ca91.png)

But if --subscribers added, duration is not works and set 100h automatically. And when check the room just publishers is in the room not subs. So it is not able to get report.

![Screen Shot 2022-11-10 at 14 41 56](https://user-images.githubusercontent.com/95404717/201082782-6a983d31-f490-4066-93fc-d02aaa2eaaa0.png)

livekit-cli version 1.2.2

**Comment by davidzhao** [comment]
I'm not able to reproduce this. Are there anything else that's notable about your setup?

```shell
% livekit-cli load-test --project local --room test-room --publishers 5 --subscribers 5 --duration 10s 
Using project: local
Starting load test with 5 video publishers, 5 subscribers, room: test-room
publishing simulcast video track - mhjhi_pub_0
publishing simulcast video track - mhjhi_pub_3
publishing simulcast video track - mhjhi_pub_1
publishing simulcast video track - mhjhi_pub_4
publishing simulcast video track - mhjhi_pub_2
Finished connecting to room, waiting 10s
```

**Comment by eyyupbgds** [comment]
I use mac. 
macOs Monterey
Version 12.6 (21G115)
livekit-cli version 1.2.2

**Comment by davidzhao** [comment]
cannot repro
