### ISSUE TITLE
Load test publishers don't trigger ActiveSpeakersChanged event

### ISSUE THREAD

**Issue by Uninen** [livekit/livekit-cli#132]
When I'm testing a LiveKit room locally running `livekit-server --dev` and `livekit-cli load-test`, the publishers don't seem to trigger the ActiveSpeakersChanged event. It would help to have at least an option to trigger that as well.

Using latest version of the server, cli, and the JS SDK running on latest macOS.

**Comment by davidzhao** [comment]
Agreed this would be nice! This should be do-able by simulating audio level with when publishing static audio files.

**Comment by davidzhao** [comment]
we do handle this now. pass in `--simulate-speakers` with load-test

**Comment by Uninen** [comment]
This is great, thanks for the feature! 👍 

There is no mention in the README about the feature, created a small PR to mention it.

**Comment by valeredev** [comment]
Hello.
Does this should work with livekit cloud? Trying to use this flag,  but the event never trigger. 

Thanks
