### ISSUE TITLE
livekit-cli 1.2.4 was not completed

### ISSUE THREAD

**Issue by chenrui333** [livekit/livekit-cli#163]
👋 even though the [goreleaser build finished successfully](https://github.com/livekit/livekit-cli/actions/runs/4599578740/jobs/8125116559), but the release was not completed somehow.

relates to https://github.com/Homebrew/homebrew-core/pull/127456

**Comment by davidzhao** [comment]
ah, it was posted as a draft. we'd have to mark it as latest. will do it now.

**Comment by davidzhao** [comment]
done! https://github.com/livekit/livekit-cli/releases/tag/v1.2.4

**Comment by chenrui333** [comment]
that was quick, thanks!
