### ISSUE TITLE
Error starting RTMP Stream

### ISSUE THREAD

**Issue by ZeroIchiro** [livekit/livekit-cli#199]
Hey guys,
we are trying to get FoundryVTT running with Livekit. Our Goal is to get RTMP up and running (egress is working according to systemctl status), however, when I try to start an egress, I get an error message:

root@livekit:/opt/livekit# livekit-cli start-room-composite-egress --request ./rtmp.json
Using default project ProjectName
twirp error internal: failed to do request: Post "http://example.com/twirp/livekit.Egress/StartRoomCompositeEgress": dial tcp 127.0.1.1:80: connect: connection refused

The RTMP.json looks like this:

`{
  "room_name": "my-room",
  "layout": "speaker-dark",
  "stream": {
    "urls": [
      "rtmp://example.com/x"
    ]
  }
}`

What do I have to do differently to make it work, so that we can import the RTMP Stream into OBS?

Kind Regards

Zero

**Comment by davidzhao** [comment]
your egress is not set up correctly. please refer to Egress docs. This is not an issue with the CLI.
