### ISSUE TITLE
[Question] My config is not working

### ISSUE THREAD

**Issue by kientv** [livekit/livekit-cli#237]
Please help to correct my config:   

root@server:/opt/livekit# livekit-cli project list
+--------+------------------------------------+-----------------+---------+
|  NAME  |                URL                 |     API KEY     | DEFAULT |
+--------+------------------------------------+-----------------+---------+
| test | http://mydomain.site:8000 | APIXKuQx9w0234dse | true    |
+--------+------------------------------------+-----------------+---------+
root@server:/opt/livekit# livekit-cli list-rooms
Using default project test
twirp error bad_route: Error from intermediary with HTTP status code 404 "Not Found"

**Comment by davidzhao** [comment]
This means your server address is incorrect. Issues are for bug reports and feature reports, not usage guidance.
