### ISSUE TITLE
1.3.3 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [livekit/livekit-cli#263]
👋 it looks like [1.3.3 release build was completed successfully](https://github.com/livekit/livekit-cli/actions/runs/7172878387), but the release did not get published. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/157248

cc @Sean-Der

**Comment by Sean-Der** [comment]
Fixed! Sorry about that @chenrui333 

Release was still in Draft

**Comment by chenrui333** [comment]
@Sean-Der thanks for the swift reply! :)You might also need to update the version info in here

https://github.com/livekit/livekit-cli/blob/59dab66bfb945206ca9a92f60c6598c4d86dee68/version.go#L18

**Comment by Sean-Der** [comment]
@chenrui333 Do I need to release a `1.3.4` or is updating it to `1.3.3` enough?

**Comment by davidzhao** [comment]
yeah we need to roll version forward

**Comment by chenrui333** [comment]
I just raised another two PRs that can help making 1.3.4 a more meaningful release :)
