### ISSUE TITLE
Does anyone try publish AV1 sucessfully work on livekit-cli with publish over TCP port ?

### ISSUE THREAD

**Issue by trgkyle** [livekit/livekit-cli#273]
Hey AV1 is the one of codec that I really interested, that optimize upto 60% bandwidth over h264, also livekit-cli support av1 ?, I checked document on livekit they told supported AV1 🤔

**Comment by davidzhao** [comment]
The CLI has not been updated to support AV1 publishing. JS, Swift, Android, Flutter SDKs currently support AV1. Python and Rust support is coming soon.

**Comment by trgkyle** [comment]
> The CLI has not been updated to support AV1 publishing. JS, Swift, Android, Flutter SDKs currently support AV1. Python and Rust support is coming soon.

Thank you so much, what about go lang ?

**Comment by davidzhao** [comment]
No plans currently.
