### ISSUE TITLE
Livekit cli egress commands not working

### ISSUE THREAD

**Issue by eyyupbgds** [livekit/livekit-cli#29]
- livekit-cli version 0.8.1
- Monterey 12.3.1

I am getting an error even though I have defined the parameters

![egress-error](https://user-images.githubusercontent.com/95404717/170962178-f35aa518-3cff-4da5-8516-0c9ce6ca2ec0.png)

**Comment by davidzhao** [comment]
looks like you are probably passing in a wrong key/secret that's somehow causing it to not pick it up. generally speaking generated api-key/api-secret are much longer than what appears on screen.

I can confirm that the command is working normally when correct parameters are passed in, closing.
