### ISSUE TITLE
livekit-cli.exe for amd64 on a windows computer installation issues

### ISSUE THREAD

**Issue by molegod** [livekit/livekit-cli#332]
When I run it, a window pops up and then just closes immediately, it does not seem to install anything properly either.

**Comment by rektdeckard** [comment]
Hi @molegod. Our Windows builds are just a binary, not an installer. After downloading and extracting, move the `lk.exe` binary to somewhere in your `%PATH%`, then execute it from the command line. A common location for this is `%LocalAppData%` (equivalent to `C:\Users\your-username\AppData\Local`).
