### ISSUE TITLE
participant does not exist

### ISSUE THREAD

**Issue by serjsv87** [livekit/livekit-cli#357]
A short bash, and you can see everything

```
root@livekit:/opt/livekit# lk room list
Using default project local
RM_G9mgLJDzAu2R jsi1-rksk       2 participants
root@livekit:/opt/livekit# lk room participants get --room jsi1-rksk
Using default project local
Using default project local
twirp error not_found: participant does not exist
root@livekit:/opt/livekit# lk room participants get --room RM_G9mgLJDzAu2R
Using default project local
Using default project local
twirp error not_found: participant does not exist
root@livekit:/opt/livekit# lk list-participants --room jsi1-rksk
Using default project local
Ssss (ACTIVE)    tracks: 2
Sergii (ACTIVE)  tracks: 2
```

**Comment by rektdeckard** [comment]
`lk room participants list jsi1-rksk` is the new commant for listing participants. `room participants get <PARTICIPANT_ID>` returns metadata for a specific participant.

**Comment by serjsv87** [comment]
I tried to get <participant_id> in room and couldn't do it through the new api and then get track details in the end I just couldn't get </participant_id> it

**Comment by rektdeckard** [comment]
Can you share the command you're trying? Full usage of the command to fetch a participant's metadata should be:

```shell
lk room participants get --room="jsi1-rksk" "Sergii"
```

**Comment by serjsv87** [comment]
Yes, it works. But how do I know that there is a user "Sergii" with the new method?

**Comment by rektdeckard** [comment]
"Sergii" appears as one of the user identities after running `lk room participants list "jsi1-rksk"`. We do not currently have an API to enumerate the metadata for all users of a room.

**Comment by serjsv87** [comment]
This is the problem in the hints, it is not clear what should be passed like this room name. it would be good to give an example or correct the hint. thanks

**Comment by rektdeckard** [comment]
Appreciate the feedback! We'll try to make the docs more clear.
