### ISSUE TITLE
Delete egress task failed

### ISSUE THREAD

**Issue by wyxzq** [livekit/livekit-cli#442]
Hi LiveKit CLI dev team!
     I need help with some error message
     I stopped the egress task using the livekit cli tool and received the following error message：
     Error stopping Egress EG_xxxx twirp error failed_precondition: egress with status EGRESS_COMPLETE cannot be stopped
twirp error failed_precondition: egress with status EGRESS_COMPLETE cannot be stopped
     The command I used is as follows：
      ./livekit-cli stop-egress --url http://ip:7880 --api-key xxxx --api-secret xxxx  --id EG_xxxx  --project test
     My version is
         version 1.5.1
  Please help me. thank

**Comment by davidzhao** [comment]
this did not fail. the Egress is already stopped and cannot be stopped again.

**Comment by wyxzq** [comment]
> this did not fail. the Egress is already stopped and cannot be stopped again.

Hello, 
the status of my egress task is EGRESS.STRARTING. I want to delete it, so I used the "stop_egress" parameter and encountered an error. 
How can I delete this egress task? 
thanks

**Comment by wyxzq** [comment]
> this did not fail. the Egress is already stopped and cannot be stopped again.
How can I modify the status of my egress task and delete it,
I cannot log in to the MySQL database to modify its status because I am not using MySQL. I am using Redis, 
as follows:
   port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
    enable_loopback_candidate: false
redis:
    address: 127.0.0.1:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
