### ISSUE TITLE
Error: "invalid cross-device link" during `lk app create` due to separate device mounts (lk version 2.3.0)

### ISSUE THREAD

**Issue by typester** [livekit/livekit-cli#492]
I tried running the sample app following the AI Agent Quickstarts guide, but I encountered an error saying `invalid cross-device link`, and I couldn’t bootstrap the app.

```
❯ lk app create --template multimodal-agent-python
Cloning template...
rename /tmp/LK_2SWPBtNipK8z my-app: invalid cross-device link
```

It seems this command doesn’t work properly when `/tmp` and `/` are on different devices. When I tried running the same command in `/tmp`, it worked without any issues, so I believe that’s likely the cause.

```
# works in /tmp
❯ lk app create --template multimodal-agent-python
Cloning template...
Instantiating environment...
Cleaning up...
To setup and run the agent:

        cd /tmp/my-app
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python3 agent.py dev
```

I briefly looked at the code but couldn’t figure out where the issue might be, so I’m leaving this as an issue here.

For reference, I’m also including the mount information for my `/tmp` and `/`:

```
/dev/nvme0n1p2 on / type f2fs (rw,relatime,lazytime,background_gc=on,nogc_merge,discard,discard_unit=block,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,barrier,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,checkpoint_merge,fsync_mode=posix,memory=normal,errors=continue)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
```

I believe using `tmpfs` for `/tmp` is a relatively common configuration in Linux, so it’s possible that many people are encountering this issue.

**Comment by rektdeckard** [comment]
Thanks for the report! We were in fact failing to relocate files when the target directory was on a different device than the temp directory (`/tmp`, or `C:\Users\<username>\AppData\Local\Temp` on Windows). This has been fixed in #490 and we'll push out a release shortly.
