### ISSUE TITLE
Loadtest issue

### ISSUE THREAD

**Issue by jason-shen** [livekit/livekit-cli#8]
in the react example app the websockets address is working as it should, but when running the load tester, i get an got websocket: bad handshake when run

below is the command i run 

./livekit-load-tester --url wss://xxx.com --api-key xxxx --api-secret xxxxxxxxx --room test --publishers 1 --subscribers 20

any help on this would be awesome

thanks advance

Jason

**Comment by davidzhao** [comment]
can you paste the full logs from the run? my guess is there's something wrong with the API key or secret.

**Comment by davidzhao** [comment]
I see the following:

```
livekit-load-tester --url ws://localhost:7880 --room myroom --publishers 1 --subscribers 2
2021/12/21 15:05:06 "level"=0 "msg"="received offer for subscriber"
2021/12/21 15:05:06 "level"=0 "msg"="ICE connected"
2021/12/21 15:05:06 "level"=0 "msg"="published track" "track"="audio"
2021/12/21 15:05:06 "level"=0 "msg"="published track" "track"="video"
2021/12/21 15:05:07 "level"=0 "msg"="received offer for subscriber"
2021/12/21 15:05:07 "level"=0 "msg"="successfully set publisher answer"
...
```

**Comment by jason-shen** [comment]
ok cool, i had to re-gen the api key again then it magically worked, but cheers for the answer as that helped me discover where the issue is
