### ISSUE TITLE
Using access token with livekit-cli

### ISSUE THREAD

**Issue by pdd-999** [livekit/livekit-cli#83]
Currently, to publish stream, `livekit-cli` requires `api-key` and `api-secret`. But for security purpose, I want to only provide `access-token`. How can I achieve this?

**Comment by davidzhao** [comment]
That's not something in scope for the CLI to support.

You can use the Go SDK directly and use [JoinWithToken](https://github.com/livekit/server-sdk-go/blob/main/room.go#L157).
